// Modelos de casa (tabla `slider_products`)
// Reutiliza las columnas del slider de sulafbc con este significado:
//  category_es      -> proyecto/colonia donde está el modelo
//  subtitle_es       -> resumen corto (dormitorios · baños · m²)
//  tagline_es         -> frase corta de venta
//  description_es    -> descripción completa del modelo
//  format_es          -> construcción (m²)
//  shelf_life_es      -> dormitorios
//  store_temp         -> baños
//  units_per_case     -> parqueos
//  logistics_es       -> precio / notas de financiamiento
//  gallery            -> galería de fotos opcional (array de rutas de imagen)
//  videos             -> videos opcionales (array de { title, description, youtubeId })
const TULIPAN_VIDEOS = [
    { title: "Recorrido interior", description: "Conocé espacios y distribución.", youtubeId: "EIwwAkCVGbM" },
    { title: "Interior del modelo", description: "Detalles del interior y acabados.", youtubeId: "gVUOeypQPq8" },
    { title: "Exterior y entorno", description: "Vista de fachada y alrededores.", youtubeId: "eVCm_bnMnpc" },
]

const TULIPAN_GALLERY = [
    "/landings/facebook/assets/img/Renders_30.png",
    "/landings/facebook/assets/img/Renders_31.png",
    "/landings/facebook/assets/img/Renders_32.png",
    "/landings/facebook/assets/img/Renders_33.png",
    "/landings/facebook/assets/img/Renders_35.png",
    "/landings/facebook/assets/img/Renders_37.png",
    "/landings/facebook/assets/img/Renders_38.png",
    "/landings/facebook/assets/img/Renders_39.png",
    "/landings/facebook/assets/img/Renders_40.png",
    "/landings/facebook/assets/img/Renders_41.png",
    "/landings/facebook/assets/img/Renders_42.png",
    "/landings/facebook/assets/img/Renders_43.png",
    "/landings/facebook/assets/img/Renders_44.png",
    "/landings/facebook/assets/img/Renders_45.png",
    "/landings/facebook/assets/img/Renders_46.png",
    "/landings/facebook/assets/img/Renders_47.png",
    "/landings/facebook/assets/img/Renders_51.png",
    "/landings/facebook/assets/img/Renders_52.png",
    "/landings/facebook/assets/img/Renders_53.png",
]

export const defaultModelos = [
    {
        slug: "tulipan",
        name_es: "Tulipán",
        name_en: "",
        image: "/landings/facebook/assets/img/Renders_30.png",
        sort_order: 1,
        category_es: "Colonia El Circilar",
        subtitle_es: "60 m² · 3 dormitorios · 2 baños",
        tagline_es: "El modelo destacado de nuestra campaña #FBSIGURBAN",
        description_es: "Tulipán es el hogar pensado para que tu familia crezca con espacio y comodidad: 3 dormitorios amplios, 2 baños completos y un parqueo techado te esperan, junto a una sala, comedor y cocina abiertos que invitan a compartir. Con 60 m² de construcción sobre un terreno de 150.60 V² (incluido en el precio) y un área de lavandería propia, cada rincón está diseñado para la vida diaria en Siguatepeque.",
        format_es: "60 m²",
        shelf_life_es: "3 dormitorios",
        store_temp: "2 baños",
        units_per_case: "1",
        logistics_es: "Precio: L 1,250,000 (terreno incluido) · Cuota desde L 6,500 · Prima 0% (promo) · Plazo hasta 30 años.",
        gallery: TULIPAN_GALLERY,
        videos: TULIPAN_VIDEOS,
    },
    {
        slug: "oocarpa",
        name_es: "Oocarpa",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/oocarpa.jpg",
        sort_order: 2,
        category_es: "Colonia El Circilar",
        subtitle_es: "91.55 m² · 3 dormitorios · 2 baños",
        tagline_es: "Amplitud y comodidad para toda la familia",
        description_es: "Modelo Oocarpa: 91.55 m² de construcción con 3 dormitorios, 2 baños, sala, comedor, cocina y área de lavandería.",
        format_es: "91.55 m²",
        shelf_life_es: "3 dormitorios",
        store_temp: "2 baños",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "modelo-anturio",
        name_es: "Anturio",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/anturio.jpg",
        sort_order: 3,
        category_es: "Colonia El Circilar",
        subtitle_es: "56 m² · 3 dormitorios · 1 baño",
        tagline_es: "Diseño moderno pensado para tu estilo de vida",
        description_es: "Modelo Anturio: 56 m² de construcción con 3 dormitorios, 1 baño, sala, comedor y cocina.",
        format_es: "56 m²",
        shelf_life_es: "3 dormitorios",
        store_temp: "1 baño",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "alamo",
        name_es: "Álamo",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/alamo.jpg",
        sort_order: 4,
        category_es: "Colonia El Circilar",
        subtitle_es: "64.09 m² · 3 dormitorios · 2 baños",
        tagline_es: "El equilibrio perfecto entre espacio y funcionalidad",
        description_es: "Modelo Álamo: 64.09 m² de construcción con 3 dormitorios, 2 baños, sala, comedor y cocina.",
        format_es: "64.09 m²",
        shelf_life_es: "3 dormitorios",
        store_temp: "2 baños",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "laurel",
        name_es: "Laurel",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/laurel.jpg",
        sort_order: 5,
        category_es: "Colonia El Circilar",
        subtitle_es: "43.20 m² · 2 dormitorios · 1 baño",
        tagline_es: "Tu primer hogar, hecho a tu medida",
        description_es: "Modelo Laurel: 43.20 m² de construcción con 2 dormitorios, 1 baño, sala, comedor y cocina.",
        format_es: "43.20 m²",
        shelf_life_es: "2 dormitorios",
        store_temp: "1 baño",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "lirio",
        name_es: "Lirio",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/lirio.jpg",
        sort_order: 6,
        category_es: "Bosques de Calanterique",
        subtitle_es: "48 m² · 2 dormitorios · 1 baño",
        tagline_es: "Diseño compacto y funcional",
        description_es: "Modelo Lirio: 48 m² de construcción con 2 dormitorios, 1 baño, sala, comedor y cocina.",
        format_es: "48 m²",
        shelf_life_es: "2 dormitorios",
        store_temp: "1 baño",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "orquidea",
        name_es: "Orquídea",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/orquidea.jpg",
        sort_order: 7,
        category_es: "Residencial Hacienda Real",
        subtitle_es: "50.31 m² · 2 dormitorios · 1 baño",
        tagline_es: "Elegancia y confort para tu familia",
        description_es: "Modelo Orquídea: 50.31 m² de construcción con 2 dormitorios, 1 baño, sala, comedor y cocina.",
        format_es: "50.31 m²",
        shelf_life_es: "2 dormitorios",
        store_temp: "1 baño",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "silvestre",
        name_es: "Silvestre",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/silvestre.jpg",
        sort_order: 8,
        category_es: "Colonia Las Teresas",
        subtitle_es: "73.71 m² · 3 dormitorios · 2 baños",
        tagline_es: "Rodeada de naturaleza",
        description_es: "Modelo Silvestre: 73.71 m² de construcción con 3 dormitorios, 2 baños, sala, comedor y cocina.",
        format_es: "73.71 m²",
        shelf_life_es: "3 dormitorios",
        store_temp: "2 baños",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "san-fernando",
        name_es: "San Fernando",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/san-fernando.jpg",
        sort_order: 9,
        category_es: "Residencial Hacienda Real",
        subtitle_es: "107.90 m² · 4 dormitorios · 2 baños",
        tagline_es: "Amplitud para familias grandes",
        description_es: "Modelo San Fernando: 107.90 m² de construcción con 4 dormitorios, 2 baños, sala, comedor, cocina y área de lavandería.",
        format_es: "107.90 m²",
        shelf_life_es: "4 dormitorios",
        store_temp: "2 baños",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
    {
        slug: "guanacaste",
        name_es: "Guanacaste",
        name_en: "",
        image: "https://apiuploads.sigurban.com/storage-api/images/modelos/2026/07/guanacaste-dba3d1.jpg",
        sort_order: 10,
        category_es: "Bosques de Calanterique",
        subtitle_es: "51.64 m² · 2 dormitorios · 1 baño",
        tagline_es: "Confort natural para tu familia",
        description_es: "Modelo Guanacaste: 51.64 m² de construcción con 2 dormitorios, 1 baño, sala, comedor y cocina.",
        format_es: "51.64 m²",
        shelf_life_es: "2 dormitorios",
        store_temp: "1 baño",
        units_per_case: "1",
        logistics_es: "Precio referencial: consultar con un asesor. Financiamiento disponible.",
    },
]
