// Proyectos inmobiliarios (tabla `products`)
export const defaultProducts = [
    {
        slug: "el-circilar",
        name_es: "Colonia El Circilar",
        name_en: "",
        image: "/images/proyectos/el-circilar.png",
        sort_order: 1,
        location_es: "Barrio Santa Martha, final calle 21 de Agosto, Siguatepeque, Comayagua (a 5 min de la CA5)",
        description_es: "Un proyecto nuevo y único en Siguatepeque, con ubicación privilegiada y excelente plusvalía.",
        description_long_es: "Un proyecto nuevo y único en Siguatepeque. Cuenta con calles vehiculares, agua potable de pozo propio, viviendas de calidad, servicios básicos completos y áreas verdes. Incluye los modelos Oocarpa, Álamo, Laurel y Anturio.",
        badge_es: "Disponible",
        maps_url: "https://maps.app.goo.gl/gmM9sghU1TiGkmMX9",
    },
    {
        slug: "bosques-de-calanterique",
        name_es: "Bosques de Calanterique",
        name_en: "",
        image: "/images/proyectos/bosques-de-calanterique.png",
        sort_order: 2,
        location_es: "Siguatepeque, Comayagua",
        description_es: "Vive en un entorno natural con seguridad y comodidad para tu familia.",
        description_long_es: "Fue el único desarrollo residencial contiguo al Parque Reserva Calanterique: 80 lotes con calles de acceso vehicular, agua potable, energía eléctrica, biodigestores certificados y áreas verdes, combinando vida residencial con preservación ambiental. Ofreció los modelos Oocarpa, Álamo, Laurel y Anturio.",
        badge_es: "Agotado",
    },
    {
        slug: "residencial-hacienda-real",
        name_es: "Residencial Hacienda Real",
        name_en: "",
        image: "/images/proyectos/residencial-hacienda-real.png",
        sort_order: 3,
        location_es: "Siguatepeque, Comayagua",
        description_es: "Exclusividad, seguridad y confort en un entorno residencial de primer nivel.",
        description_long_es: "Fue una comunidad residencial de 97 lotes en una zona estratégica de alta plusvalía, con fácil acceso a centros comerciales, colegios, clínicas y hospitales. Contó con calles pavimentadas, agua potable, energía eléctrica, alcantarillado sanitario, áreas verdes, circuito cerrado de vigilancia y caseta de seguridad. Ofreció los modelos Oocarpa, Álamo, Laurel y Anturio.",
        badge_es: "Agotado",
    },
    {
        slug: "las-teresas",
        name_es: "Colonia Las Teresas",
        name_en: "",
        image: "/images/proyectos/las-teresas.png",
        sort_order: 4,
        location_es: "Noroeste del Primer Batallón de Ingenieros, Siguatepeque, Comayagua",
        description_es: "Vive rodeado de naturaleza y seguridad en un entorno familiar.",
        description_long_es: "Fue un proyecto de lotificación y venta de terrenos con financiamiento garantizado y cuotas bajas. Contó con canchas deportivas, parques, puesto de bomberos, posta policial, escuela, centro de salud e iglesia, en una zona tranquila rodeada de los pinares de la ciudad. Ofreció los modelos Oocarpa, Álamo, Laurel y Anturio.",
        badge_es: "Agotado",
    },
]
